version: "3.8"

services:
  web-app:
    build:
      context: ./ArgoCD-Web-App
      dockerfile: Dockerfile
    network_mode: "host"
    restart: always
    depends_on:
      - mongo

  cronjob:
    build:
      context: ./ArgoCD-Monitor-Cronjob
      dockerfile: Dockerfile
    restart: always
    network_mode: "host"
    depends_on:
      - mongo
      - redis
  
  notification:
    build:
      context: ./Notifications
      dockerfile: Dockerfile
    restart: always
    network_mode: "host"
    depends_on:
      - mongo
      - nats
  
  slack:
    build:
      context: ./Slack
      dockerfile: Dockerfile
    restart: always
    network_mode: "host"
    depends_on:
      - mongo
      - nats
    
  email:
    build:
      context: ./Email
      dockerfile: Dockerfile
    restart: always
    network_mode: "host"
    depends_on:
      - mongo
      - nats

  mongo: # mongosh --username mongouser --password mongopassword 
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
    volumes:
      - mongo_test:/data/db
    restart: always
    network_mode: host  # Use the host network mode
    
  redis:
    image: "redis:7.2.3-alpine"
    restart: always
    network_mode: host  # Use the host network mode

  nats:
    image: nats:latest
    restart: always
    network_mode: host  # Use the host network mode
    
volumes:
  mongo_test: