version: "3.8"  # Use the desired Docker Compose version
services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
    ports:
      - "27017:27017"
# To login in docker container
# mongosh --username mongouser --password mongopassword
