version: "3.8"
services:
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
    volumes:
      - mongo_test:/data/db
    network_mode: host  # Use the host network mode

volumes:
  mongo_test: