name: CI - ArgoCD-Monitor

on:
  push:
    branches:
      - main
    paths:
      - 'app/server/ArgoCD/ArgoCD-Monitor-Cronjob/**'
  pull_request:
    branches:
      - main
    paths:
      - 'app/server/ArgoCD/ArgoCD-Monitor-Cronjob/**'
      
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Build Packages
        working-directory: ./app/server/ArgoCD/ArgoCD-Monitor-Cronjob
        run: go build -v ./...     
      
      - name: Run Test Cases
        working-directory: ./app/server/ArgoCD/ArgoCD-Monitor-Cronjob/controller_test
        run: go test ./... -v
        
      - name: Build Docker Image
        working-directory: ./app/server/ArgoCD/ArgoCD-Monitor-Cronjob
        run: docker build . --file Dockerfile --tag argocd-monitor-cronjob  
