name: CI - ArgoCD-Web-App

on:
  push:
    branches:
      - main
    paths:
      - 'app/server/ArgoCD/ArgoCD-Web-App/**'
  pull_request:
    branches:
      - main
    paths:
      - 'app/server/ArgoCD/ArgoCD-Web-App/**'
      
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Build Packages
        working-directory: ./app/server/ArgoCD/ArgoCD-Web-App
        run: go build -v ./...     
      
      - name: Run Test Cases
        working-directory: ./app/server/ArgoCD/ArgoCD-Web-App/controller_test
        run: go test ./... -v 
        
      - name: Build Docker Image
        working-directory: ./app/server/ArgoCD/ArgoCD-Web-App
        run: docker build . --file Dockerfile --tag argocd-web-app
