name: CI - Slack

on:
  push:
    branches:
      - main
    paths:
      - 'app/server/ArgoCD/Slack/**'
  pull_request:
    branches:
      - main
    paths:
      - 'app/server/ArgoCD/Slack/**'
      
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: pkg build
        working-directory: ./app/server/ArgoCD/Slack
        run: go build -v ./...     
      
      #- name: Run Tests
      #  run: go test ./... 
